name: AchievementIgnore
version: ${project.version}
main: ru.armagidon.achievementignore.AchievementIgnore
api-version: 1.14
depend: [ProtocolLib]
commands:
  ignoreachievements:
    aliases: [aignore]
